% --------------------------------------------------
% AMG : Atomic Model Generation
% --------------------------------------------------
clear   all;
close   all;
addpath Source

%% Set parameters for rendering resolution and Chimera environments
param.chi_exe = '"C:\Program Files\Chimera 1.10.2\bin\chimera.exe"';
param.chi_win = '"C:\Program Files\Chimera 1.10.2\bin\chimera.exe"';
param.chi_opt = '--silent --script';

param.size     = [800 800];
param.proj     = 'orthographic';    % [orthographic | perspective]
param.color    = 'defined';         % [defined | multiple]
param.out      = 'all';             % cmd / tif / all
param.type     = 'molmap'           % molmap or ribbon
param.view     = 'xy';              % Viewpoints, xy, yz, xyz
param.scale    = 1.0;               % Scale
param.bulge    = 1;                 % 0 - no bulge, 1 - with bulge
param.cndo     = 2;                 % cndo format version
param.trans    = 0.0;               % Transparency (0.0(original) ~ 1.0)
param.mol_res  = 3;                 % Parameter for molmap
param.vol_step = 1;                 % Parameter for volume step

%% Step 5. Set problem name with array
name_prob = {...
'01_Plate_Cross_1cs_42bp_max_16_cndo',...
'02_Honeycomb_1cs_42bp_max_16_cndo',...
'03_Wheel_1cs_42bp_max_16_cndo',...
'04_Circle_1cs_42bp_max_16_cndo',...
'05_Ellipse_1cs_27bp_max_16_cndo',...
'06_Rhombic_Tiles_1cs_84bp_max_16_cndo',...
'07_L_Shape_1cs_42bp_max_16_cndo',...
'08_Cross_1cs_42bp_max_16_cndo',...
'09_Quarter_Circle_1cs_42bp_max_16_cndo',...
'10_Disk_1cs_35bp_max_16_cndo',...
'11_Cairo_Penta_Tiles_1cs_42bp_max_16_cndo',...
'12_Prismatic_Penta_Tiles_1cs_42bp_max_16_cndo',...
'13_Hexagonal_Mesh_1cs_42bp_max_16_cndo',...
'14_Hepta_Penta_Tiles_1cs_42bp_max_16_cndo',...
'15_Lotus_1cs_36bp_max_16_cndo',...
'16_4_Sided_Polygon_1cs_84bp_max_16_cndo',...
'17_5_Sided_Polygon_1cs_84bp_max_16_cndo',...
'18_6_Sided_Polygon_1cs_84bp_max_16_cndo',...
'19_Plate_Quad_1cs_84bp_max_16_cndo',...
'20_Plate_Tri_1cs_84bp_max_16_cndo',...
'21_Plate_Eng_1cs_84bp_max_16_cndo',...
'22_L_shape_42bp_1cs_42bp_max_16_cndo',...
'23_L_shape_63bp_1cs_63bp_max_16_cndo',...
'24_L_shape_84bp_1cs_84bp_max_16_cndo',...
}

%% Step 6. Generate the atomic model
for i = 1 : numel(name_prob)
    tic;
    disp(strcat('     # Problem name : ', name_prob{i}))
    path_input{i}  = fullfile('Input\', strcat(name_prob{i}, '.cndo'));
    path_output{i} = strcat('Output\', name_prob{i});
    main_cndo2pdb(path_input{i}, path_output{i}, param);
    toc;
end