% --------------------------------------------------
% AMG : Atomic Model Generation
% --------------------------------------------------
clear   all;
close   all;
addpath Source

%% Set parameters for rendering resolution and Chimera environments
param.molmapResolution = 3;
param.WindowSize       = [800 800];
param.chimeraEXE       = '"C:\Program Files\Chimera 1.10.2\bin\chimera.exe"';
param.chimeraEXE_win   = '"C:\Program Files\Chimera 1.10.2\bin\chimera.exe"';
param.chimeraOPTION    = '--silent --script';
param.fileType         = 'all';     % cmd / tif / all
param.bulge            = 1;         % 0 - no bulge, 1 - with bulge
param.cndo             = 2;         % cndo format version

%% Step 5. Set problem name with array
name_prob = {...
'01_Plate_Uniform_Quad_1cs_42bp_beveled_max',...
'02_Plate_Uniform_Tri_1cs_42bp_beveled_max',...
'03_Quarter_Circle_Quad_1cs_42bp_beveled_max',...
'04_Disk_Quad_1cs_42bp_beveled_max',...
'05_Circle_Tri_Coarse_1cs_42bp_beveled_max',...
'06_Ellipse_Tri_Coarse_1cs_42bp_beveled_max',...
'07_L_Shape_Regular_1cs_42bp_beveled_max',...
'08_Hexagonal_Mesh_1cs_42bp_beveled_max',...
'09_Honeycomb_1cs_42bp_beveled_max',...
'10_Stickman_1cs_42bp_beveled_max',...
'11_End_Cube_Quad_1cs_42bp_beveled_max',...
'12_End_Pentagonal_Prism_Quad_1cs_42bp_beveled_max',...
'13_End_Cylinder_Quad_1cs_42bp_beveled_max',...
'14_Cooling_Tower_Tri_1cs_31bp_beveled_max',...
'15_Hemisphere_Quad_1cs_31bp_beveled_max',...
'16_Prism_Octagonal_1cs_42bp_beveled_max',...
'17_Prism_Enneagonal_1cs_42bp_beveled_max',...
'18_Antiprism_Pentagonal_1cs_42bp_beveled_max',...
'19_Antiprism_Hexagonal_1cs_42bp_beveled_max',...
'20_Antiprism_Heptagonal_1cs_42bp_beveled_max',...
'21_Square_Pyramid_J1_1cs_42bp_beveled_max',...
'22_Penta_Pyramid_J2_1cs_42bp_beveled_max',...
'23_Penta_Cupola_J5_1cs_42bp_beveled_max',...
'24_Gyro_Square_Cupola_J23_1cs_42bp_beveled_max',...
'25_Gyro_Penta_Cupola_J24_1cs_42bp_beveled_max',...
'26_Chiral_Bi_Pro_Tetrahedron_1cs_42bp_beveled_max',...
'27_Chiral_Bi_Pro_Cube_1cs_42bp_beveled_max',...
'28_Chiral_Bi_Pro_Octahedron_1cs_31bp_beveled_max',...
'29_Chiral_Bi_Snub_Cube_1cs_42bp_beveled_max',...
'30_Chiral_Bi_Penta_Icositetrahedron_1cs_31bp_beveled_max'}

%% Step 6. Generate the atomic model
for i = 1 : numel(name_prob)
    tic;
    disp(strcat('     # Problem name : ', name_prob{i}))
    path_input{i}  = fullfile('Input\', strcat(name_prob{i}, '.cndo'));
    path_output{i} = strcat('Output\', name_prob{i});
    main_cndo2pdb(path_input{i}, path_output{i}, param);
    toc;
end